<?php

namespace Database\Seeders;

use Faker\Generator as Faker;
use Illuminate\Database\Seeder;
use App\Models\Nationality;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(Faker $faker)
    {
        $nationality = array(
            array('id' => 1, 'code' => '0300', 'name' => 'Bangladeshi'),
            array('id' => 2, 'code' => '0050', 'name' => 'Albanese'),
            array('id' => 3, 'code' => '0100', 'name' => 'Algerijnse'),
            array('id' => 4, 'code' => '0223', 'name' => 'Amerikaans burger'),
            array('id' => 5, 'code' => '0437', 'name' => 'Amerikaans onderdaan'),
            array('id' => 6, 'code' => '0051', 'name' => 'Andorrese'),
            array('id' => 7, 'code' => '0101', 'name' => 'Angolese'),
            array('id' => 8, 'code' => '0251', 'name' => 'Argentijnse'),
            array('id' => 9, 'code' => '0300', 'name' => 'Afghaanse'),
            array('id' => 10, 'code' => '0040', 'name' => 'Armeense'),
            array('id' => 11, 'code' => '0400', 'name' => 'Australische'),
            array('id' => 12, 'code' => '0039', 'name' => 'Azerbeidzjaanse'),
            array('id' => 13, 'code' => '0200', 'name' => 'Bahamaanse'),
            array('id' => 14, 'code' => '0301', 'name' => 'Bahreinse'),
            array('id' => 15, 'code' => '0251', 'name' => 'Barbadaanse'),
            array('id' => 16, 'code' => '0038', 'name' => 'Belarussische'),
            array('id' => 17, 'code' => '0052', 'name' => 'Belgische'),
            array('id' => 18, 'code' => '0202', 'name' => 'Belizaanse'),
            array('id' => 19, 'code' => '0345', 'name' => 'Afghaanse'),
            array('id' => 20, 'code' => '0111', 'name' => 'Beninse'),
            array('id' => 21, 'code' => '0302', 'name' => 'Bhutaanse'),
            array('id' => 22, 'code' => '0252', 'name' => 'Boliviaanse'),
            array('id' => 23, 'code' => '0105', 'name' => 'Botswaanse'),
            array('id' => 24, 'code' => '0253', 'name' => 'Braziliaanse'),
            array('id' => 25, 'code' => '0060', 'name' => 'Brits'),
            array('id' => 26, 'code' => '0304', 'name' => 'Bruneise'),
            array('id' => 27, 'code' => '0053', 'name' => 'Bulgaarse'),
            array('id' => 28, 'code' => '0421', 'name' => 'Burger van Antigua en Barbuda'),
            array('id' => 29, 'code' => '0029', 'name' => 'Burger van Bosnië-Herzegovina'),
            array('id' => 30, 'code' => '0110', 'name' => 'Burger van Congo'),
            array('id' => 31, 'code' => '0106', 'name' => 'Burkinese'),
            array('id' => 32, 'code' => '0303', 'name' => 'Burmaanse'),
            array('id' => 33, 'code' => '0104', 'name' => 'Burundese'),
            array('id' => 34, 'code' => '0305', 'name' => 'Cambodjaanse'),
            array('id' => 35, 'code' => '0204', 'name' => 'Canadese'),
            array('id' => 36, 'code' => '0108', 'name' => 'Centraal-Afrikaanse'),
            array('id' => 37, 'code' => '0254', 'name' => 'Chileense'),
            array('id' => 38, 'code' => '0307', 'name' => 'Chinese'),
            array('id' => 39, 'code' => '0255', 'name' => 'Colombiaanse'),
            array('id' => 40, 'code' => '0109', 'name' => 'Comorese'),
            array('id' => 41, 'code' => '0205', 'name' => 'Costa Ricaanse'),
            array('id' => 42, 'code' => '0206', 'name' => 'Cubaanse'),
            array('id' => 43, 'code' => '0308', 'name' => 'Cyprische'),
            array('id' => 44, 'code' => '0054', 'name' => 'Deense'),
            array('id' => 45, 'code' => '0115', 'name' => 'Djiboutiaanse'),
            array('id' => 46, 'code' => '0207', 'name' => 'Dominicaanse'),
            array('id' => 47, 'code' => '0256', 'name' => 'Ecuadoraanse'),
            array('id' => 48, 'code' => '0112', 'name' => 'Egyptische'),
            array('id' => 49, 'code' => '0113', 'name' => 'Equatoriaal-Guinese'),
            array('id' => 50, 'code' => '0084', 'name' => 'Eritrese'),
            array('id' => 51, 'code' => '0045', 'name' => 'Estische'),
            array('id' => 52, 'code' => '0141', 'name' => 'Eswatinische'),
            array('id' => 53, 'code' => '0114', 'name' => 'Ethiopische'),
            array('id' => 54, 'code' => '0425', 'name' => 'Fijische'),
            array('id' => 55, 'code' => '0309', 'name' => 'Filipijnse'),
            array('id' => 56, 'code' => '0056', 'name' => 'Finse'),
            array('id' => 57, 'code' => '0057', 'name' => 'Franse'),
            array('id' => 58, 'code' => '0116', 'name' => 'Gabonese'),
            array('id' => 59, 'code' => '0117', 'name' => 'Gambiaanse'),
            array('id' => 60, 'code' => '0030', 'name' => 'Georgische'),
            array('id' => 61, 'code' => '0118', 'name' => 'Ghanese'),
            array('id' => 62, 'code' => '0267', 'name' => 'Grenadaanse'),
            array('id' => 63, 'code' => '0059', 'name' => 'Griekse'),
            array('id' => 64, 'code' => '0211', 'name' => 'Guatemalaanse'),
            array('id' => 65, 'code' => '0139', 'name' => 'Guinee-Bissause'),
            array('id' => 66, 'code' => '0119', 'name' => 'Guinese'),
            array('id' => 67, 'code' => '0259', 'name' => 'Guyaanse'),
            array('id' => 68, 'code' => '0212', 'name' => 'Haïtiaanse'),
            array('id' => 69, 'code' => '0213', 'name' => 'Hondurese'),
            array('id' => 70, 'code' => '0061', 'name' => 'Hongaarse'),
            array('id' => 71, 'code' => '0062', 'name' => 'Ierse'),
            array('id' => 72, 'code' => '0063', 'name' => 'IJslandse'),
            array('id' => 73, 'code' => '0312', 'name' => 'Indiase'),
            array('id' => 74, 'code' => '0313', 'name' => 'Indonesische'),
            array('id' => 75, 'code' => '0314', 'name' => 'Iraakse'),
            array('id' => 76, 'code' => '0315', 'name' => 'Iraanse'),
            array('id' => 77, 'code' => '0316', 'name' => 'Israëlische'),
            array('id' => 78, 'code' => '0064', 'name' => 'Italiaanse'),
            array('id' => 79, 'code' => '0120', 'name' => 'Ivoriaanse'),
            array('id' => 80, 'code' => '0214', 'name' => 'Jamaicaanse'),
            array('id' => 81, 'code' => '0317', 'name' => 'Japanse'),
            array('id' => 82, 'code' => '0058', 'name' => 'Jemenitische'),
            array('id' => 83, 'code' => '0065', 'name' => 'Joegoslavische'),
            array('id' => 84, 'code' => '0319', 'name' => 'Jordaanse'),
            array('id' => 85, 'code' => '0121', 'name' => 'Kaapverdische'),
            array('id' => 86, 'code' => '0122', 'name' => 'Kameroense'),
            array('id' => 87, 'code' => '0037', 'name' => 'Kazachse'),
            array('id' => 88, 'code' => '0123', 'name' => 'Kenyaanse'),
            array('id' => 89, 'code' => '0035', 'name' => 'Kirgizische'),
            array('id' => 90, 'code' => '0445', 'name' => 'Kiribatische'),
            array('id' => 91, 'code' => '0320', 'name' => 'Koeweitse'),
            array('id' => 92, 'code' => '0087', 'name' => 'Kosovaarse'),
            array('id' => 93, 'code' => '0043', 'name' => 'Kroatische'),
            array('id' => 94, 'code' => '0321', 'name' => 'Laotiaanse'),
            array('id' => 95, 'code' => '0125', 'name' => 'Lesothaanse'),
            array('id' => 96, 'code' => '0044', 'name' => 'Letse'),
            array('id' => 97, 'code' => '0322', 'name' => 'Libanese'),
            array('id' => 98, 'code' => '0126', 'name' => 'Liberiaanse'),
            array('id' => 99, 'code' => '0127', 'name' => 'Libische'),
            array('id' => 100, 'code' => '0066', 'name' => 'Liechtensteinse'),
            array('id' => 101, 'code' => '0046', 'name' => 'Litouwse'),
            array('id' => 102, 'code' => '0067', 'name' => 'Luxemburgse'),
            array('id' => 103, 'code' => '0086', 'name' => 'Macedonische'),
            array('id' => 104, 'code' => '0128', 'name' => 'Malagassische'),
            array('id' => 105, 'code' => '0129', 'name' => 'Malawische'),
            array('id' => 106, 'code' => '0324', 'name' => 'Maldivische'),
            array('id' => 107, 'code' => '0325', 'name' => 'Maleisische'),
            array('id' => 108, 'code' => '0130', 'name' => 'Malinese'),
            array('id' => 109, 'code' => '0068', 'name' => 'Maltese'),
            array('id' => 110, 'code' => '0131', 'name' => 'Marokkaanse'),
            array('id' => 111, 'code' => '0047', 'name' => 'Marshalleilandse'),
            array('id' => 112, 'code' => '0132', 'name' => 'Mauritaanse'),
            array('id' => 113, 'code' => '0216', 'name' => 'Mexicaanse'),
            array('id' => 114, 'code' => '0443', 'name' => 'Micronesische'),
            array('id' => 115, 'code' => '0036', 'name' => 'Moldavische'),
            array('id' => 116, 'code' => '0069', 'name' => 'Monegaskische'),
            array('id' => 117, 'code' => '0326', 'name' => 'Mongolische'),
            array('id' => 118, 'code' => '0455', 'name' => 'Montenegrijnse'),
            array('id' => 119, 'code' => '0134', 'name' => 'Mozambikaanse'),
            array('id' => 120, 'code' => '0048', 'name' => 'Myanmarese'),
            array('id' => 121, 'code' => '0049', 'name' => 'Namibische'),
            array('id' => 122, 'code' => '0431', 'name' => 'Nauruaanse'),
            array('id' => 123, 'code' => '0001', 'name' => 'Nederlandse'),
            array('id' => 124, 'code' => '0328', 'name' => 'Nepalese'),
            array('id' => 125, 'code' => '0218', 'name' => 'Nicaraguaanse'),
            array('id' => 126, 'code' => '0402', 'name' => 'Nieuw-Zeelandse'),
            array('id' => 127, 'code' => '0136', 'name' => 'Nigerese'),
            array('id' => 128, 'code' => '0137', 'name' => 'Nigeriaanse'),
            array('id' => 129, 'code' => '0318', 'name' => 'Noord-Jemenitische'),
            array('id' => 130, 'code' => '0329', 'name' => 'Noord-Koreaanse'),
            array('id' => 131, 'code' => '0070', 'name' => 'Noorse'),
            array('id' => 132, 'code' => '0034', 'name' => 'Oekraïense'),
            array('id' => 133, 'code' => '0033', 'name' => 'Oezbeekse'),
            array('id' => 134, 'code' => '0327', 'name' => 'Omaanse'),
            array('id' => 135, 'code' => '0071', 'name' => 'Oostenrijkse'),
            array('id' => 136, 'code' => '0331', 'name' => 'Pakistaanse'),
            array('id' => 137, 'code' => '0432', 'name' => 'Palause'),
            array('id' => 138, 'code' => '0219', 'name' => 'Panamese'),
            array('id' => 139, 'code' => '0401', 'name' => 'Papoea-Nieuw-Guinese'),
            array('id' => 140, 'code' => '0261', 'name' => 'Paraguayaanse'),
            array('id' => 141, 'code' => '0262', 'name' => 'Peruaanse'),
            array('id' => 142, 'code' => '0072', 'name' => 'Poolse'),
            array('id' => 143, 'code' => '0073', 'name' => 'Portugese'),
            array('id' => 144, 'code' => '0333', 'name' => 'Qatarese'),
            array('id' => 145, 'code' => '0074', 'name' => 'Roemeense'),
            array('id' => 146, 'code' => '0041', 'name' => 'Russische'),
            array('id' => 147, 'code' => '0143', 'name' => 'Rwandese'),
            array('id' => 148, 'code' => '0447', 'name' => 'Saint Luciaanse'),
            array('id' => 149, 'code' => '0442', 'name' => 'Salomonseilandse'),
            array('id' => 150, 'code' => '0208', 'name' => 'Salvadoraanse'),
            array('id' => 151, 'code' => '0405', 'name' => 'Samoaanse'),
            array('id' => 152, 'code' => '0076', 'name' => 'San Marinese'),
            array('id' => 153, 'code' => '0334', 'name' => 'Saoedi-Arabische'),
            array('id' => 154, 'code' => '0145', 'name' => 'Senegalese'),
            array('id' => 155, 'code' => '0454', 'name' => 'Servische'),
            array('id' => 156, 'code' => '0444', 'name' => 'Seychelse'),
            array('id' => 157, 'code' => '0147', 'name' => 'Sierra Leoonse'),
            array('id' => 158, 'code' => '0335', 'name' => 'Singaporese'),
            array('id' => 159, 'code' => '0042', 'name' => 'Sloveense'),
            array('id' => 160, 'code' => '0027', 'name' => 'Slowaakse'),
            array('id' => 161, 'code' => '0148', 'name' => 'Soedanese'),
            array('id' => 162, 'code' => '0149', 'name' => 'Somalische'),
            array('id' => 163, 'code' => '0077', 'name' => 'Spaanse'),
            array('id' => 164, 'code' => '0306', 'name' => 'Sri Lankaanse'),
            array('id' => 165, 'code' => '0263', 'name' => 'Surinaamse'),
            array('id' => 166, 'code' => '0135', 'name' => 'Swazische'),
            array('id' => 167, 'code' => '0336', 'name' => 'Syrische'),
            array('id' => 168, 'code' => '0032', 'name' => 'Tadzjiekse'),
            array('id' => 169, 'code' => '0310', 'name' => 'Taiwanese'),
            array('id' => 170, 'code' => '0151', 'name' => 'Tanzaniaanse'),
            array('id' => 171, 'code' => '0337', 'name' => 'Thaise'),
            array('id' => 172, 'code' => '0152', 'name' => 'Togolese'),
            array('id' => 173, 'code' => '0430', 'name' => 'Tongaanse'),
            array('id' => 174, 'code' => '0154', 'name' => 'Tsjadische'),
            array('id' => 175, 'code' => '0028', 'name' => 'Tsjechische'),
            array('id' => 176, 'code' => '0155', 'name' => 'Tunesische'),
            array('id' => 177, 'code' => '0031', 'name' => 'Turkmeense'),
            array('id' => 178, 'code' => '0339', 'name' => 'Turkse'),
            array('id' => 179, 'code' => '0446', 'name' => 'Tuvaluaanse'),
            array('id' => 180, 'code' => '0138', 'name' => 'Ugandese'),
            array('id' => 181, 'code' => '0264', 'name' => 'Uruguayaanse'),
            array('id' => 182, 'code' => '0424', 'name' => 'Vanuatuaanse'),
            array('id' => 183, 'code' => '0079', 'name' => 'Vaticaanse'),
            array('id' => 184, 'code' => '0265', 'name' => 'Venezolaanse'),
            array('id' => 185, 'code' => '0342', 'name' => 'Vietnamese'),
            array('id' => 186, 'code' => '0404', 'name' => 'West-Samoaanse'),
            array('id' => 187, 'code' => '0124', 'name' => 'Zaïrese'),
            array('id' => 188, 'code' => '0156', 'name' => 'Zambiaanse'),
            array('id' => 189, 'code' => '0142', 'name' => 'Zimbabwaanse'),
            array('id' => 190, 'code' => '0140', 'name' => 'Zuid-Afrikaanse'),
            array('id' => 191, 'code' => '0340', 'name' => 'Zuid-Jemenitische'),
            array('id' => 192, 'code' => '0341', 'name' => 'Zuid-Koreaanse'),
            array('id' => 193, 'code' => '0157', 'name' => 'Zuid-Soedanese '),
            array('id' => 194, 'code' => '0080', 'name' => 'Zweedse'),
            array('id' => 195, 'code' => '0081', 'name' => 'Zwitserse'),
        );

        $unixTimestamp = time();
        foreach ($nationality as $key => $value) :

            $nationality = new Nationality();
            $nationality->code = $value['code'];
            $nationality->name = $value['name'];


            $nationality->save();
        endforeach;
    }
}
